[package]
name = "iron-gcd"
version = "0.1.0"
authors = ["huohongbo"]

[dependencies]
iron = "0.2.2"
mime = "0.1.0"
router = "0.0.15"
urlencoded = "0.3.0"

[dependencies.bodyparser]

git = "https://github.com/iron/body-parser.git"
